name: "ci"

on:
  repository_dispatch:
    types: [update-request]
  workflow_dispatch:

jobs:
  testhello:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Executed!"
  buildrelease:
    name: "Build release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "develop"
      - name: "Download main program"
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "PrepPipe/preppipe-python"
          tag: "latest"
          fileName: "preppipe_cli-windows-x64.exe"
          tarBall: false
          zipBall: false
          out-file-path: "dist"
      - name: "Download GUI"
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "PrepPipe/preppipe_gui"
          tag: "latest"
          fileName: "preppipe_gui-windows-x64.7z"
          tarBall: false
          zipBall: false
          out-file-path: "dist"
      - name: "Update main branch"
        shell: bash
        run: |
          git checkout --orphan latest_branch
          git add -A
          git commit -am "Auto-update"
          git branch -D main
          git branch -m main
          git gc
          git push -f origin main
