name: "ci"

on:
  repository_dispatch:
    types: [update-request]
  workflow_dispatch:

jobs:
  buildrelease:
    name: "Build release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "develop"
          persist-credentials: false
      - name: "Download main program"
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "PrepPipe/preppipe-python"
          tag: "latest"
          fileName: "preppipe_cli-windows-x64.exe"
          tarBall: false
          zipBall: false
          out-file-path: "dist"
      - name: "Download GUI"
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "PrepPipe/preppipe_gui"
          tag: "latest"
          fileName: "preppipe_gui-windows-x64.7z"
          tarBall: false
          zipBall: false
          out-file-path: "dist"
      - name: "Update main branch"
        shell: bash
        run: |
          git config --global user.email "xsj617603321@gmail.com"
          git config --global user.name "Shengjie Xu"
          git checkout --orphan latest_branch
          git add -A
          git commit -am "Auto-update"
          git branch -M main
          git gc
      - name: "Push to main"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PREPPIPE_ALL_IN_ONE_PAT }}
          branch: "main"
          force: true
