name: steam

on:
  workflow_dispatch:

jobs:
  deployToSteam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read Version
        run: |
          echo "PPVERSION=$(cat VERSION.txt)" >> $GITHUB_ENV
          echo "PPVERSION=${{ env.PPVERSION }}"
      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          appId: ${{ secrets.STEAM_APP_ID }}
          buildDescription: ${{ env.PPVERSION }}
          #rootPath: build
          depot1Path: windows-x64
          releaseBranch: prerelease
