name: "sync"

on:
  push:
    branches:
      - "main"

jobs:
  sync2gitee:
    name: "Sync to Gitee"
    runs-on: ubuntu-latest
    steps:
      - name: Organization mirror
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/preppipe
          dst: gitee/preppipe
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          force_update: true
